[metadata]
name = teal-ravenframework
version = 0.6rc1
description = TEAL plugin for RAVEN framework
long_description = file: TEAL/README.md
license_files = TEAL/LICENSE.txt TEAL/NOTICE.txt
url = https://github.com/idaholab/TEAL

[options]
packages =
    TEAL
    TEAL/src
python_requires = >=3.9

install_requires =
   raven_framework >=3.1rc1
   numpy-financial

